-- CreateTable
CREATE TABLE "InitiativeAccess" (
    "id" TEXT NOT NULL,
    "initiativeId" TEXT NOT NULL,
    "userId" TEXT,
    "teamId" TEXT,
    "permission" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "InitiativeAccess_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "InitiativeAccess_initiativeId_userId_key" ON "InitiativeAccess"("initiativeId", "userId");

-- CreateIndex
CREATE UNIQUE INDEX "InitiativeAccess_initiativeId_teamId_key" ON "InitiativeAccess"("initiativeId", "teamId");

-- AddForeignKey
ALTER TABLE "InitiativeAccess" ADD CONSTRAINT "InitiativeAccess_initiativeId_fkey" FOREIGN KEY ("initiativeId") REFERENCES "Initiative"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "InitiativeAccess" ADD CONSTRAINT "InitiativeAccess_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "InitiativeAccess" ADD CONSTRAINT "InitiativeAccess_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Hand-added (not machine-generated by `prisma migrate diff`, which has no
-- @@check DSL primitive): enforce "exactly one of userId/teamId" at the
-- database level, matching docs/V2-RESOURCE-ACCESS.md's grantee rule. This is
-- additive validation on a brand-new, empty table — it cannot invalidate any
-- existing row.
-- AddCheckConstraint
ALTER TABLE "InitiativeAccess" ADD CONSTRAINT "InitiativeAccess_grantee_xor" CHECK (
    (("userId" IS NOT NULL)::int + ("teamId" IS NOT NULL)::int) = 1
);
