"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import Button from "@/components/ui/Button";
import Input from "@/components/ui/Input";
import Textarea from "@/components/ui/Textarea";
import { apiFetch } from "@/lib/clientApi";

type TargetType = "feature" | "story" | "bug" | "sprint" | "release";
type Option = { key: string; type: TargetType; id: string; label: string };
type Blocker = { id: string; blockerType: string; description: string; status: string; revision: number; owner: { name: string } | null; targetLabel: string };
type Dependency = { id: string; predecessorLabel: string; dependentLabel: string; dependencyType: string; description: string };

export default function DependencyBlockerBoard({ initiativeId, options, blockers, dependencies }: { initiativeId: string; options: Option[]; blockers: Blocker[]; dependencies: Dependency[] }) {
  const router = useRouter(); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false);
  const [predecessor, setPredecessor] = useState(options[0]?.key ?? ""); const [dependent, setDependent] = useState(options[1]?.key ?? ""); const [dependencyDescription, setDependencyDescription] = useState("");
  const [target, setTarget] = useState(options[0]?.key ?? ""); const [blockerType, setBlockerType] = useState("dependency"); const [description, setDescription] = useState("");
  const selected = (key: string) => options.find((option) => option.key === key);
  async function addDependency() { const from = selected(predecessor); const to = selected(dependent); if (!from || !to) return; setPending(true); setError(null); const result = await apiFetch(`/api/initiatives/${initiativeId}/dependencies`, { method: "POST", body: { predecessor: { type: from.type, id: from.id }, dependent: { type: to.type, id: to.id }, dependencyType: "depends_on", description: dependencyDescription } }); setPending(false); if (!result.ok) return setError(result.error ?? "Couldn't add dependency."); setDependencyDescription(""); router.refresh(); }
  async function addBlocker() { const item = selected(target); if (!item) return; setPending(true); setError(null); const result = await apiFetch(`/api/initiatives/${initiativeId}/blockers`, { method: "POST", body: { target: { type: item.type, id: item.id }, blockerType, description } }); setPending(false); if (!result.ok) return setError(result.error ?? "Couldn't add blocker."); setDescription(""); router.refresh(); }
  async function changeStatus(blocker: Blocker, status: string) { const reason = status === "resolved" ? "Blocker resolved during planning" : "Blocker status updated"; setPending(true); setError(null); const result = await apiFetch(`/api/blockers/${blocker.id}`, { method: "PATCH", body: { expectedRevision: blocker.revision, status, ...(status === "resolved" ? { resolution: "Resolution confirmed by the Product Owner." } : {}), reason } }); setPending(false); if (!result.ok) return setError(result.error ?? "Couldn't update blocker."); router.refresh(); }
  return <section className="mt-8 space-y-4"><div><h3 className="text-lg font-semibold">Dependencies and blockers</h3><p className="text-sm text-neutral-500">Record cross-item sequencing and unresolved impediments. Circular dependencies are rejected.</p></div>{error && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="grid gap-4 xl:grid-cols-2"><div className="rounded-xl border bg-white p-4"><h4 className="font-semibold">Add dependency</h4><div className="mt-3 grid gap-2"><select className="rounded-lg border px-3 py-2 text-sm" value={predecessor} onChange={(event) => setPredecessor(event.target.value)}>{options.map((item) => <option key={item.key} value={item.key}>{item.label}</option>)}</select><span className="text-center text-xs text-slate-500">must finish before</span><select className="rounded-lg border px-3 py-2 text-sm" value={dependent} onChange={(event) => setDependent(event.target.value)}>{options.map((item) => <option key={item.key} value={item.key}>{item.label}</option>)}</select><Input placeholder="Dependency note (optional)" value={dependencyDescription} onChange={(event) => setDependencyDescription(event.target.value)} /><Button disabled={pending || !predecessor || !dependent} onClick={addDependency}>Add dependency</Button></div><div className="mt-4 space-y-2">{dependencies.map((item) => <p key={item.id} className="rounded-lg bg-slate-50 p-2 text-sm"><b>{item.predecessorLabel}</b> → {item.dependentLabel}{item.description ? <span className="block text-xs text-slate-500">{item.description}</span> : null}</p>)}</div></div><div className="rounded-xl border bg-white p-4"><h4 className="font-semibold">Record blocker</h4><div className="mt-3 grid gap-2"><select className="rounded-lg border px-3 py-2 text-sm" value={target} onChange={(event) => setTarget(event.target.value)}>{options.map((item) => <option key={item.key} value={item.key}>{item.label}</option>)}</select><Input placeholder="Blocker type" value={blockerType} onChange={(event) => setBlockerType(event.target.value)} /><Textarea placeholder="What is blocked and what must happen?" value={description} onChange={(event) => setDescription(event.target.value)} /><Button disabled={pending || !target || !description.trim()} onClick={addBlocker}>Add blocker</Button></div><div className="mt-4 space-y-2">{blockers.map((item) => <div key={item.id} className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm"><p className="font-semibold">{item.targetLabel} · {item.blockerType}</p><p className="mt-1">{item.description}</p><div className="mt-2 flex items-center justify-between gap-2"><span className="text-xs capitalize text-amber-800">{item.status.replaceAll("_", " ")}{item.owner ? ` · ${item.owner.name}` : ""}</span>{item.status !== "resolved" && <Button variant="secondary" disabled={pending} onClick={() => changeStatus(item, "resolved")}>Resolve</Button>}</div></div>)}</div></div></div></section>;
}
