import { db } from "@/lib/db";
import { getAiCapabilityConfig } from "@/lib/ai/registry";
import { ContextBudgetExceededError, ContextScopeMismatchError } from "@/lib/ai/errors";
import type { AiActionKey } from "@/lib/ai/types";
import { loadApprovedFeaturesTier, loadInitiativeContextTier, loadProjectContextTier, loadWorkspaceContextTier } from "./loaders";
import { estimateTokens, trimToBudget } from "./tokenBudget";
import type { AssembledContext, ContextAudit, ContextLayer, ContextTier } from "./types";

// Section 5 §4 — the centralized context-assembly orchestrator. Every AI
// Assist action routes through this (via src/lib/ai/assist/runAction.ts)
// instead of hand-building its own workspace/project/initiative context.
//
// What this does NOT do: replace each action's own task-specific query with
// a generic mega-loader. `extraTiers` is that task-specific data — e.g.
// proposeStoryContent.ts's specific feature + its current epic/story tree —
// passed in as-is, still the smallest useful package for that one task
// (§3). This module only wraps it with the right workspace/project/
// initiative tiers and enforces the budget/audit trail around it.

export interface AssembleAiContextParams {
  action: AiActionKey;
  organizationId: string;
  projectId: string | null;
  initiativeId: string | null;
  /** The calling action's own task-specific tiers (layer "task" or
   * "artifact") — always treated as required; never generated by this
   * module. */
  extraTiers?: ContextTier[];
}

/** Ids are refused as a set, not accepted individually — a request whose
 * initiativeId doesn't actually belong to the given projectId, or whose
 * projectId doesn't belong to the given organizationId, never gets as far
 * as loading anything. This is independent of (not a replacement for) the
 * route-level access guard, which only confirms the signed-in user may act
 * on the given initiative — this confirms the ids themselves are
 * internally consistent. */
async function assertOwnershipChain(params: AssembleAiContextParams): Promise<void> {
  if (params.initiativeId) {
    const initiative = await db.initiative.findUnique({
      where: { id: params.initiativeId },
      select: { projectId: true, organizationId: true },
    });
    if (!initiative || initiative.organizationId !== params.organizationId || initiative.projectId !== params.projectId) {
      throw new ContextScopeMismatchError(
        `Initiative "${params.initiativeId}" does not belong to project "${params.projectId}" / organization "${params.organizationId}".`,
      );
    }
    return;
  }
  if (params.projectId) {
    const project = await db.project.findUnique({ where: { id: params.projectId }, select: { organizationId: true } });
    if (!project || project.organizationId !== params.organizationId) {
      throw new ContextScopeMismatchError(
        `Project "${params.projectId}" does not belong to organization "${params.organizationId}".`,
      );
    }
  }
}

async function loadDeclaredTier(
  layer: ContextLayer,
  required: boolean,
  params: AssembleAiContextParams,
): Promise<ContextTier | null> {
  switch (layer) {
    case "workspace":
      return { ...(await loadWorkspaceContextTier(params.organizationId)), required };
    case "project":
      return params.projectId ? { ...(await loadProjectContextTier(params.projectId)), required } : null;
    case "initiative":
      return params.initiativeId ? { ...(await loadInitiativeContextTier(params.initiativeId)), required } : null;
    // "artifact"/"task" are never auto-loaded — they're always the caller's
    // own extraTiers, per this module's header comment.
    default:
      return null;
  }
}

export async function assembleAiContext(params: AssembleAiContextParams): Promise<AssembledContext> {
  await assertOwnershipChain(params);

  const config = await getAiCapabilityConfig(params.action);
  if (!config) throw new Error(`No AiCapability registry entry for action "${params.action}".`);

  const autoTiers: ContextTier[] = [];
  for (const layer of config.requiredContextLayers) {
    const tier = await loadDeclaredTier(layer, true, params);
    if (tier) autoTiers.push(tier);
  }
  for (const layer of config.optionalContextLayers) {
    if (config.requiredContextLayers.includes(layer)) continue; // already loaded as required above
    const tier = await loadDeclaredTier(layer, false, params);
    if (tier) autoTiers.push(tier);
  }
  // "Approved features" rides alongside the initiative layer whenever it's
  // in play — §2 lists "features" directly under Initiative Context.
  if (params.initiativeId && config.requiredContextLayers.includes("initiative")) {
    autoTiers.push({ ...(await loadApprovedFeaturesTier(params.initiativeId)), required: true });
  } else if (params.initiativeId && config.optionalContextLayers.includes("initiative")) {
    autoTiers.push({ ...(await loadApprovedFeaturesTier(params.initiativeId)), required: false });
  }

  const allTiers = [...autoTiers, ...(params.extraTiers ?? [])];
  const { tiers: keptTiers, overBudget } = trimToBudget(allTiers, config.maxContextTokens);

  const audit: ContextAudit = {
    organizationId: params.organizationId,
    projectId: params.projectId,
    initiativeId: params.initiativeId,
    recordsLoaded: keptTiers.map((t) => ({ layer: t.layer, type: t.sourceType, id: t.sourceId, version: t.sourceVersion })),
    overBudget,
  };

  if (overBudget) {
    throw new ContextBudgetExceededError(
      `Required context for "${params.action}" exceeds the configured limit (${config.maxContextTokens} tokens) — nothing was sent.`,
      audit,
    );
  }

  const text = keptTiers.map((t) => `## ${t.label}\n${t.content}`).join("\n\n");
  return { tiers: keptTiers, text, estimatedTokens: estimateTokens(text), audit };
}
